[build]
  command = "npx @aws-amplify/cli init --yes --amplify "{\
\"projectName\":\"charitychooser\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}" && npm run build"
  functions = "functions/"

[[plugins]]
  package = "@netlify/plugin-nextjs"
